"""Initial migration

Revision ID: 24e488500f58
Revises: 2cc58b0f726a
Create Date: 2025-09-09 05:42:44.827074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e488500f58'
down_revision = '2cc58b0f726a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('finalized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('finalized')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
